LanchesMac/ViewModels/HomeViewModel.cs
using LanchesMac.Models;

namespace LanchesMac.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Lanche> LanchesPreferidos { get; set; }
    }
}

LanchesMac/Controllers/CarrinhoCompraController.cs
using LanchesMac.Models;
using LanchesMac.Repositories.Interfaces;
using LanchesMac.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace LanchesMac.Controllers
{
    public class CarrinhoCompraController : Controller
    {
        private readonly ILancheRepository _lancheRepository;
        private readonly CarrinhoCompra _carrinhoCompra;

        public CarrinhoCompraController(ILancheRepository lancheRepository,
            CarrinhoCompra carrinhoCompra)
        {
            _lancheRepository = lancheRepository;
            _carrinhoCompra = carrinhoCompra;
        }

        public IActionResult Index()
        {
            var itens = _carrinhoCompra.GetCarrinhoCompraItens();
            _carrinhoCompra.CarrinhoCompraItems = itens;

            var carrinhoCompraVM = new CarrinhoCompraViewModel
            {
                CarrinhoCompra = _carrinhoCompra,
                CarrinhoCompraTotal = _carrinhoCompra.GetCarrinhoCompraTotal()
            };

            return View(carrinhoCompraVM);
        }
        public IActionResult AdicionarItemNoCarrinhoCompra(int lancheId)
        {
            var lancheSelecionado = _lancheRepository.Lanches
                                    .FirstOrDefault(p => p.LancheId == lancheId);

            if (lancheSelecionado != null)
            {
                _carrinhoCompra.AdicionarAoCarrinho(lancheSelecionado);
            }
            return RedirectToAction("Index");
        }

        public IActionResult RemoverItemDoCarrinhoCompra(int lancheId)
        {
            var lancheSelecionado = _lancheRepository.Lanches
                                    .FirstOrDefault(p => p.LancheId == lancheId);

            if (lancheSelecionado != null)
            {
                _carrinhoCompra.RemoverDoCarrinho(lancheSelecionado);
            }
            return RedirectToAction("Index");
        }
    }
}

LanchesMac/Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;

namespace LanchesMac.Controllers
{
    public class ContatoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

LanchesMac/Views/Contato/Index.cshtml
<div class="container">
    <img src="~/images/faleconosco1.jpg" alt="Fale conosco" />
    <div class="jumbotron">
        <h3>Queremos ouvir o que você tem a dizer</h3>
        <p>
            Se você tiver alguma dúvida ou sugestão fale conosco
        </p>
        <p>
            <span>
                <img src="~/images/Envelope-icon24.png" />
            </span>
            <h5><email endereco="helio.msj@outlook.com" conteudo="Enviar um e-mail"></email></h5>
            <br />
            <span>
                <img src="~/images/phone-app-icon.png" />
            </span>
            <h5>(11) 9874-5566</h5>
            <br />
            <span>
                <img src="~/images/Home-iconred.png" />
            </span>
            <h5>Av. Juscelino Kubichek 1000 - 03540-550 - São Paulo</h5>
        </p>
    </div>
</div>

LanchesMac/Views/Home/Index.cshtml
@model HomeViewModel

<partial name="_Carousel" />

<h2>Os preferidos da semana </h2>
<h4>Tá com fome ??</h4>

<div class="row">
    @foreach(var lanche in Model.LanchesPreferidos)
    {
        <partial name="_LanchesResumo" for="@lanche"/>
    }
</div>

LanchesMac/Views/Shared/Components/CarrinhoCompraResumo/Default.cshtml
@model CarrinhoCompraViewModel

@if(Model.CarrinhoCompra.CarrinhoCompraItems.Count > 0)
{
    <a asp-controller="CarrinhoCompra"asp-action="Index">
        <span><img src="~/images/cart-5-16.ico"/></span>
        <span style="color:white">
            @Model.CarrinhoCompra.CarrinhoCompraItems.Count
        </span>
    </a>
}

LanchesMac/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LanchesMac</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LanchesMac.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
       <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    LanchesMac
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @await Component.InvokeAsync("CarrinhoCompraResumo")
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    <a class="nav-link text-light" asp-area="" asp-controller="Lanche" asp-action="List">Lanches</a>
                    <a class="nav-link text-light" asp-area="" asp-controller="Contato" asp-action="Contato">Lanches</a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - LanchesMac - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>